version: '3'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: treetest-db
    environment:
      - POSTGRES_DB=treetest
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - treetest

  app:
    build: .
    depends_on:
      db:
        condition: service_started
    networks:
      - treetest

networks:
  treetest: