spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://db:5432/treetest
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: jdbc:postgresql://db:5432/treetest
  schemas: treetest
  user: test
  password: test

