spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://postgres:5432/treetest
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: jdbc:postgresql://postgres:5432/treetest
  schemas: treetest
  user: admin
  password: admin

