CREATE TABLE materialized_path (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   path VARCHAR(255) NOT NULL,
   CONSTRAINT pk_materialized_path PRIMARY KEY (id)
);

CREATE INDEX IDX_PATH ON materialized_path(path);